#!/usr/bin/env python3
import argparse
import asyncio
import socketio
import sys

sio = socketio.Client()

@sio.event
def translation(text):
    print(text)
    sio.disconnect()
    exit(0)

if __name__ == '__main__':
    parser = argparse.ArgumentParser(description="Translate text")
    parser.add_argument("text", help="quoted text in Japanese")
    parser.add_argument("-p", "--port", type=int, default=8080, help="port number to use, default is 8080")
    args = parser.parse_args()

    try:
        sio.connect(f'http://localhost:{args.port}', auth={'text': args.text}, transports=['polling'])
    except socketio.exceptions.ConnectionError:
        pass
